Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/Encoding:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/GuardClause:
  Enabled: false
Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
